CREATE MULTISET TABLE PE_DESA_FG_CONFIG.TB_ESTADO ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      EstadoCD SMALLINT TITLE 'EstadoCD' NOT NULL,
      CodEstado VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'CodEstado',
      DesEstado VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC FORMAT 'X(30)' TITLE 'DesEstado',
      TipoEstado VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC TITLE 'TipoEstado',
      FecCreaTS TIMESTAMP(6) TITLE 'FecCreaTS')
PRIMARY INDEX ( EstadoCD );